// Generated by CoffeeScript 1.4.0

/*
  ヾ(ΦωΦ=)にゃーにゃーにゃー
*/


(function() {
  var _this = this;

  $(function() {
    var $header, $necoContainer, $necoLoader, $pageTop, $sns, $thumbneco, $win, IDs, addMouseEvents, ag, contents, ie, ios, isIos, isJump, isPc, loaded, mOut, mOver, max, necoBuild, necoJump, necoLoad, necoTag, pTopImgs, resizeHandler, setWidth, setupPageTop, _isAnimated;
    $header = $('#header');
    $necoLoader = $('#necoLoader');
    $necoContainer = $('#necoContainer');
    $pageTop = $('#pageTop');
    $thumbneco = $('.thumbneco');
    $win = $(window);
    $sns = $('#sns');
    max = 40;
    _isAnimated = true;
    loaded = false;
    isJump = false;
    ios = false;
    IDs = [];
    necoTag = 'ねこ';
    pTopImgs = ['images/j1.gif', 'images/j2.gif', 'images/j3.gif'];
    ie = false;
    contents = '';
    ag = navigator.userAgent;
    isIos = function() {
      ios = true;
      $('.box').css({
        '-webkit-transition-duration': '0s',
        '-moz-transition-duration': '0s',
        '-ms-transition-duration': '0s',
        '-o-transition-duration': '0s',
        'transition-duration': '0s'
      });
      return _isAnimated = false;
    };
    isPc = function() {
      return $thumbneco.css({
        '-webkit-mask-image': 'url(../images/circle.png)',
        '-webkit-mask-size': '280px',
        '-webkit-mask-repeat': 'no-repeat',
        '-webkit-mask-position': 'center'
      });
    };
    if (ag.indexOf('iPhone') > 0 && ag.indexOf('iPad') === -1 || ag.indexOf('iPad') > 0 || ag.indexOf('Android') > 0) {
      isIos();
    } else {
      isPc();
    }
    if (ag.search(/Safari/) !== -1) {
      if (ag.search(/Chrome/) !== -1) {
        $('#copyright').css({
          'letter-spacing': '-0.1em'
        });
      }
    } else if (ag.search(/MSIE 10/) !== -1 || ag.search(/MSIE 9/) !== -1 || ag.search(/MSIE 8/) !== -1) {
      ie = true;
    }
    $sns.hide();
    $('#login').hide();
    $necoLoader.css({
      'left': $win.width() / 2 - 30 + 'px',
      'top': $win.height() / 2 - 100 + 'px'
    });
    $necoLoader.fadeIn(500);
    setWidth = function() {
      var $ww;
      $ww = $win.width();
      if ($ww >= 1200) {
        return $necoContainer.width($ww);
      } else if ($ww < 1200 && $ww > 960) {
        return $necoContainer.width(960);
      } else if ($ww < 950 && $ww > 720) {
        return $necoContainer.width(720);
      } else if ($ww < 720 && $ww > 480) {
        return $necoContainer.width(480);
      } else if ($ww < 480) {
        return $necoContainer.width(280);
      }
    };
    resizeHandler = function() {
      setWidth();
      if (!ios) {
        if (loaded) {
          $necoContainer.masonry('destroy');
        }
      }
      return $necoContainer.masonry({
        itemSelector: '.box',
        isAnimated: _isAnimated
      });
    };
    $win.resize(resizeHandler);
    necoLoad = function() {
      setWidth();
      return $.ajax({
        url: "https://api.instagram.com/v1/tags/" + necoTag + "/media/recent?client_id=f39149070d2d4c5fb73cdddcaf00e0dd",
        data: {
          count: max.toString()
        },
        dataType: 'jsonp',
        error: function(jqXHR, textStatus, errorThrown) {
          return $necoContainer.text(textStatus);
        },
        success: function(data, textStatus, jqXHR) {
          return necoBuild(data);
        }
      });
    };
    necoLoad();
    necoBuild = function(data) {
      var capsText, content, i, len, link, url, user, _data, _i;
      i = 0;
      len = data.data.length;
      user = '';
      link = '';
      url = '';
      capsText = '';
      _data = {};
      for (i = _i = 0; 0 <= max ? _i <= max : _i >= max; i = 0 <= max ? ++_i : --_i) {
        _data = data.data[i];
        try {
          if (_data.images.thumbnail.url === void 0) {
            url = _data.images.thumbnail;
          } else {
            url = _data.images.thumbnail.url;
          }
        } catch (e) {
          url = '#';
        }
        try {
          link = _data.link;
        } catch (e) {
          link = '#';
        }
        try {
          user = _data.user;
        } catch (e) {
          user = {
            'profile_picture': '',
            'username': ''
          };
        }
        try {
          capsText = _data.caption.text;
        } catch (e) {
          capsText = '';
        }
        link = link.replace("instagr.am", "instagram.com");
        if (link !== '#' || url !== '#') {
          content = '<div class="box image shadow" id="' + _data.id + '">' + '<a href="' + link + '" target="_blank">' + '<img class="thumbneco" src="' + url + '" width="200" />' + '</a><br />' + '<div class="description">' + '<a href="http://instagram.com/' + user.username + '" target="_blank">' + '<img class="thumbnail" src="' + user.profile_picture + '" width="30" />' + '<p class="username"><strong>' + user.username + '</strong></p>' + '</a>' + '<p class="caption">' + capsText + '</p>' + '</div>' + '</div>';
          contents += content;
          if (max !== 1) {
            if (i === (len - 1)) {
              $necoContainer.append(contents);
            }
            IDs.push(user.id);
          } else {
            if (IDs[0] !== user.id) {
              IDs.unshift(user.id);
              $necoContainer.prepend(content);
              setTimeout(function() {
                resizeHandker();
                return $necoContainer.find('.image').css({
                  'opacity': '1'
                });
              }, 1000);
            }
          }
        }
      }
      return setTimeout(function() {
        max = 1;
        return necoLoad();
      }, 5000);
    };
    necoJump = function() {
      isJump = true;
      setTimeout(function() {
        return $pageTop.find('img').attr('src', pTopImgs[2]);
      }, 300);
      $pageTop.off('mouseover', mOver).off('mouseout', mOut).off('click', necoJump).stop().animate({
        'right': '100px',
        'bottom': $win.height() + 'px'
      }, 1500, 'easeInOutExpo', setupPageTop);
      return $('body,html').animate({
        scrollTop: 0
      }, 1200, 'easeInOutExpo');
    };
    mOver = function() {
      return $pageTop.find('img').attr('src', pTopImgs[1]);
    };
    mOut = function() {
      return $pageTop.find('img').attr('src', pTopImgs[0]);
    };
    setupPageTop = function() {
      isJump = false;
      return $pageTop.on('mouseover', mOver).on('mouseout', mOut).on('click', necoJump).css({
        'right': '0',
        'bottom': '-90px'
      }).find('img').attr('src', pTopImgs[0]);
    };
    setupPageTop();
    $win.scroll(function() {
      if ($(this).scrollTop() > 500) {
        if (!isJump) {
          return $pageTop.stop().animate({
            'bottom': '0px'
          }, 300);
        }
      } else {
        if (!isJump) {
          return $pageTop.stop().animate({
            'bottom': '-80px'
          }, 300);
        }
      }
    });
    window.onload = function() {
      $('.image').css({
        'top': '500px',
        'left': $win.width() / 2 - 200 + 'px'
      });
      $necoContainer.append($sns);
      $header.animate({
        'top': '0'
      }, 800);
      return $necoLoader.fadeOut(800, function() {
        $necoLoader.remove();
        $necoContainer.masonry({
          itemSelector: '.box',
          isAnimated: _isAnimated
        });
        $necoContainer.find('.image').css('opacity', '1');
        $sns.show();
        $pageTop.show();
        addMouseEvents();
        resizeHandler();
        return loaded = true;
      });
    };
    addMouseEvents = function() {
      if (!ios) {
        $thumbneco.live('mouseover', function() {
          return $(this).stop().transition({
            "-webkit-mask-size": "200px"
          }, 50, 'ease-out').css({
            transform: "rotate(5deg)"
          }).closest('.image').stop().transition({
            'background-color': '#f2f0f0',
            '-webkit-border-top-left-radius': '110px',
            '-moz-border-radius-topleft': '110px',
            '-webkit-border-top-right-radius': '110px',
            '-moz-border-radius-topright': '110px'
          }, 50, 'ease-out');
        });
        $thumbneco.live('mouseout', function() {
          return $(this).stop().transition({
            "-webkit-mask-size": "280px"
          }, 30, 'ease-out').css({
            transform: "rotate(0deg)"
          }).closest('.image').stop().transition({
            'background-color': '#ffffff',
            '-webkit-border-top-left-radius': '10px',
            '-moz-border-radius-topleft': '10px',
            '-webkit-border-top-right-radius': '10px',
            '-moz-border-radius-topright': '10px'
          }, 30, 'ease-out');
        });
        $('#icon').hover(function() {
          $(this).fadeTo(0, 0.8);
          return $('#me').fadeIn(200);
        }, function() {
          $(this).fadeTo(0, 1);
          return $('#me').fadeOut(200);
        });
        $('#icon').click(function() {
          return $('#me').fadeOut(0);
        });
        return $('.description').hover(function() {
          return $(this).find('.thumbnail').css({
            'border': '1px solid #8c7e7e'
          }).end().find('.username').css('color', '#8c7e7e');
        }, function() {
          return $(this).find('.thumbnail').css({
            'border': '1px solid #ccc'
          }).end().find('.username').css('color', '#444444');
        });
      }
    };
    return _this;
  });

}).call(this);
